<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="head_unit">

  <xacro:property name="pi" value="3.14159265359" />

  <link name="head_unit">
    <visual>
      <geometry>
        <box size="0.0160528 0.1992376 0.119888"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1" />
      </material>
    </visual>
  </link>

  <joint name="base_link_to_head_unit" type="fixed">
    <parent link="base_link" />
    <child link="head_unit" />
    <origin xyz="0 0 1.2192" rpy="0 0 0" />
  </joint>


  <!-- Bot platforms -->

<!--
  <xacro:macro name="platform" params="pos">
    <link name="platform_${pos}">
      <visual>
        <geometry>
          <box size="${platform_l} ${platform_w} ${platform_h}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1" />
        </material>
      </visual>
    </link>
  </xacro:macro>
  <xacro:platform pos="base" />
  <xacro:platform pos="upper" />
  <xacro:macro name="platform_joint" params="pos xyz">
    <joint name="platform_joint_${pos}" type="fixed">
      <parent link="base_link" />
      <child link="platform_${pos}" />
      <origin xyz="${xyz}" rpy="0 0 0" />
    </joint>
  </xacro:macro>
  <xacro:platform_joint pos="base" xyz="0 0 ${wheel_r + wheel_h_offset}" />
  <xacro:platform_joint pos="upper" xyz="0 0 ${wheel_r + wheel_h_offset + 0.08}" />

<link name="kinect_link">
  <visual>
    <geometry>
      <box size="0.064 0.121 0.0381" />
    </geometry>
    <material name="Blue" />
  </visual>
  <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" 
               izz="0.0001" />
  </inertial>
</link>
-->


<!--
<node pkg="tf" type="static_transform_publisher" name="device_to_depth_cam" args="0 0 0 0 0.24 0 device depth_camera 10"/>
<node pkg="tf" type="static_transform_publisher" name="fisheye_to_depth_cam" args="0 -0.05 0 0 0 0 depth_camera fisheye_camera 10"/>
-->
</robot>
