<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_base">

  <xacro:property name="platform_l" value=".2032" />
  <xacro:property name="platform_w" value=".2286" />
  <xacro:property name="platform_h" value=".0064" />
  <xacro:property name="wheel_r" value=".0328" />
  <xacro:property name="wheel_l" value=".0267" />
  <xacro:property name="wheel_w_offset" value=".0025" />
  <xacro:property name="wheel_h_offset" value="-.015" />
  <xacro:property name="pi" value="3.14159265359" />

  <!-- fictitious center point on ground and between wheels for navigation -->
  <link name="base_footprint">
    <visual>
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <material name="black">
        <color rgba="0 0 0 1" />
      </material>
    </visual>
  </link>
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1" />
      </material>
    </visual>
  </link>

  <link name="platform">
    <visual>
      <geometry>
        <box size="${platform_l} ${platform_w} ${platform_h}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1" />
      </material>
    </visual>
  </link>

  <link name="wheel_left">
    <visual>
      <geometry>
        <cylinder radius="${wheel_r}" length="${wheel_l}" />
      </geometry>
      <origin rpy="${pi / 2} 0 0" />
      <material name="black">
        <color rgba="0 0 0 1" />
      </material>
    </visual>
  </link>
  <link name="wheel_right">
    <visual>
      <geometry>
        <cylinder radius="${wheel_r}" length="${wheel_l}" />
      </geometry>
      <origin rpy="${(pi / 2) * -1} 0 0" />
      <material name="black">
        <color rgba="0 0 0 1" />
      </material>
    </visual>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${wheel_r}" rpy="0 0 0" />
  </joint>
  <joint name="platform_joint" type="fixed">
    <parent link="base_link" />
    <child link="platform" />
    <origin xyz="0 0 ${wheel_r + wheel_h_offset}" rpy="0 0 0" />
  </joint>
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_left" />
    <axis xyz="0 1 0" />
    <origin rpy="0 0 0" xyz="0 ${(platform_w / 2) + (wheel_l / 2) + wheel_w_offset} 0" />
  </joint>
  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_right" />
    <axis xyz="0 1 0" />
    <origin rpy="0 0 0" xyz="0 ${((platform_w / 2) + (wheel_l / 2) + wheel_w_offset) * -1} 0" />
  </joint>
</robot>

